### PR TITLE
Moving the role diagram to standard, vector-based tooling

### PR DESCRIPTION
**Pull request by msdemlei**
The original role diagram here is a PNG for some reason.  To make later maintenance simpler, I'd suggest using what ivoatex gives you -- and that's what this PR does.

It'll conflict with the parallel PR #12 because both add dependencies to the moc.pdf target.  Resolution is simple: just join the two dependency lines.

Speaking of conflicts: I'd take out moc.lof and moc.lot out of the repo.  They are generated files, and while having them in the repo has zero benefit, they'll produce no end of conflicts down the road.

### CODE REVIEW

**Comment by tomdonaldson** [comment]
Thanks @msdemlei .  This is clearly an improvement in handling this.

I am a little confused about the intended workflow however.  A good version of `role_diagram.pdf` is in the repository, but it is overwritten by `make`.  In my environment, and in the environment used by the CI, the generated `role_diagram.pdf` contains error text: 

> PDF fallback: A conversion from SVG to PDF failed. This is probably because inkscape is not installed. While SVG is not supported by the major TeX engines, it is recommended to commit built PDFs to the VCS.

If there is a way to update environments to build the pdf correctly, then should the pdf not be in the repo?  Alternatively, with the pdf in the repo, should the Makefile be updated to not regenerate it?

**Comment by msdemlei** [comment]
On Mon, Dec 13, 2021 at 06:57:43PM -0800, Tom wrote:
> I am a little confused about the intended workflow however.  A good
> version of `role_diagram.pdf` is in the repository, but it is
> overwritten by `make`.  In my environment, and in the environment

It should only be overwritten by make if role_diagram.svg is newer
than the PDF, which it shouldn't... I've hope.  Hm: I'll have to read
up on git's management of mtimes.

> used by the CI, the generated `role_diagram.pdf` contains error
> text: 
> 
> > PDF fallback: A conversion from SVG to PDF failed. This is
> > probably because inkscape is not installed. While SVG is not
> > supported by the major TeX engines, it is recommended to commit
> > built PDFs to the VCS.
> 
> If there is a way to update environments to build the pdf
> correctly, then should the pdf not be in the repo?  Alternatively,
> with the pdf in the repo, should the Makefile be updated to not
> regenerate it?

So, regrettably SVG tooling hasn't been all that great so far, with
inkscape being the only reliable way I had found to convert SVG to
PDF without rendering to pixels.  Hence the recommendation to commit
the PDF *in addition to* the SVG, as inkscape is a rather heavy
dependency.

Fortunately, in Debian bullseye, this has changed; there's rsvg in
there now.  I'll introduce it into ivoatex RSN, at which point the CI
can be fixed to use it, which means we can much more easily live
without PDFs in the repos.  Which, yes, is clearly desirable, as
I agree that build artefacts should in general not be committed.

**Comment by tomdonaldson** [comment]
> It should only be overwritten by make if role_diagram.svg is newer than the PDF, which it shouldn't... I've hope. Hm: I'll have to read up on git's management of mtimes.

This does seem to be the issue.  Git doesn't keep track of mtimes at all, so I suppose whether the svg is newer than the pdf is fairly random.  So far in my environment and the github actions that generate the preview, svg must have been slightly older.  I can imagine several kludgy workarounds, including adding a `touch role_diagram.pdf` in the github actions setup.  One thing that is really not obvious to me is why this doesn't seem to be happening in the handful of other document repos I've checked (like ivoa-std/MeasurementDM).

**Review by tomdonaldson — APPROVED** [review]
I'm inclined to go ahead and merge this, and use a subsequent PR to work around the role_diagram problem in the preview build.

**Comment by tomdonaldson** [comment]
It turns out that the main problem was that `role_diagram.svg` was not in the repo, so it was being regenerated every time, which in turn made it always newer than `role_diagram.pdf`.  I've added it to the repo in #14, which seems to address the problem for now, if in a slightly fragile way.

**Pull request merged**
